global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: minio-job
    metrics_path: /minio/prometheus/metrics
    static_configs:
      - targets: ['Minio1:9000', 'Minio2:9000', 'Minio3:9000', 'Minio4:9000']

  - job_name: vmware-job
    metrics_path: /metrics
    static_configs:
      - targets: ['VMWareExporter:9272']
