global:
  scrape_interval: 5m
  evaluation_interval: 5m

  external_labels:
    monitor: 'KJDev.PublicServices1'

scrape_configs:
  - job_name: emmc1
    static_configs:
      - targets: ['emmc1Exporter:8000']

  - job_name: minio-job
    metrics_path: /minio/prometheus/metrics
    static_configs:
      - targets: ['Minio1:9000', 'Minio2:9000', 'Minio3:9000', 'Minio4:9000']

  - job_name: vmware-job
    dns_sd_configs:
      - names:
          - tasks.VMWareExporter
        type: 'A'
        port: 9272
