global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: emmc1
    static_configs:
      - targets: ['emmc1Exporter:8000']
